# chatbot_responses.py

responses = {
    "namaste": "Namaste! How can I assist you today?",
    "hello bot": "Hello! How can I assist you today?",
    "nice to meet you": "Nice to meet you too! How can I help you today?",
    "good morning": "Good morning! How can I assist you today?",
    "good evening": "Good evening! How can I assist you today?",
    "good afternoon": "Good afternoon! What can I do for you?",
    "good evening": "Good evening! How can I help you?",
    "hello": "Hello! How can I help you today?",
    "hi there": "Hi there! How can I assist you?",
    "hi bot": "Hello! How can I assist you today?",
    "hey": "Hey! How can I help you today?",
    "how are you": "I’m just a bot, but I’m here to help you!",
    "hey there": "Hey there! What can I do for you?",
    "howdy": "Howdy! How can I assist you today?",
    "hi": "Hi there! What can I do for you?",
    "help": "Sure! You can ask me about invoices, orders, payments, and more.",
    "invoice status": "Invoices are processed within 24 hours. Need help with a specific one?",
    "order status": "Orders are processed quickly. Need help with a specific order?",
    "process time": "Most processes are completed within 24 hours. Need help with something specific?",
    "order details": "Orders can be tracked in the Orders section. Need help?",
    "payment status": "Payments are tracked daily. Any issues with yours?",
    "invoice details": "Invoices are available in the Invoices section. Need help?",
    "order details": "Orders can be tracked in the Orders section. Need help?",
    "payment details": "Payments are listed in the Payments section. Need help?",
    "invoice query": "Invoices are handled promptly. What do you want to know?",
    "invoice": "Invoices are handled promptly. What do you want to know?",
    "order": "Orders are processed quickly. Need help with a specific order?",
    "payment": "Payments are tracked daily. Any issues with yours?",
    "status": "Your request is being processed. Please wait a moment.",
    "report": "Reports are available under the Reports section. Need help?",
    "analytics": "Analytics provide insights on your data. What do you want to explore?",
    "cash": "Cash applications are processed within 24 hours.",
    "dispute": "Disputes are reviewed carefully. How can I assist with a dispute?",
    "delivery": "Deliveries usually arrive within 3-5 business days.",
    "refund": "Refunds are handled according to company policy. Need details?",
    "thanks": "You’re welcome! Anything else I can assist with?",
    "thank you": "Glad to help! Let me know if you need more info.",
    "bye": "Goodbye! Have a great day.",
    "goodbye": "See you soon! Feel free to come back anytime.",
    "who are you": "I’m your friendly assistant bot here to help.",
    "what can you do": "I can answer questions about orders, invoices, payments, and more.",
    "default": "Sorry, I didn't get that. Could you please rephrase?",
    "status": "Your request is being processed. Please wait a moment.",
    "report": "Reports are available under the Reports section. Need help?",
    "analytics": "Analytics provide insights on your data. What do you want to explore?",
    "cash": "Cash applications are processed within 24 hours.",
    "dispute": "Disputes are reviewed carefully. How can I assist with a dispute?",
    "delivery": "Deliveries usually arrive within 3-5 business days.",
    "refund": "Refunds are handled according to company policy. Need details?",
    "complaint": "We take complaints seriously. Please provide details.",
    "feedback": "We appreciate your feedback! Please share your thoughts.",
    "issue": "Please describe the issue you are facing.",
    "support": "Our support team is here 24/7. How can I connect you?",
    "issue": "Can you please provide more details about the issue?",
    "contact": "You can contact support at support@example.com.",
    "payment status": "Please provide your invoice number to check payment status.",
    "order status": "Provide your order ID to check its current status.",
    "update": "Updates are posted regularly on the dashboard.",
    "thanks for help": "Happy to help! Reach out anytime.",
    "thank you very much": "You’re very welcome!",
    "ok": "Okay, noted!",
    "sure": "Great! What’s next?",
    "no": "Alright, let me know if you change your mind.",
    "yes": "Understood. How can I assist further?",
    "can you help me": "Absolutely! Please tell me your question.",
    "hello bot": "Hi! Ready to assist you.",
    "good morning": "Good morning! How can I brighten your day?",
    "good night": "Good night! Sleep well and reach out tomorrow.",
    "how are you": "I’m just a bot, but I’m here to help you!",
    "how's it going": "I’m doing well, thanks! How can I assist you?",
    "what's your name": "I’m your virtual assistant. You can call me Bot.",
    "what's the time": "I’m not sure about the time, but I’m here to help!",
    "what's the date": "I can’t check the date, but I’m here for your queries.",
    "where are you": "I exist in the cloud, always ready to assist you.",
    "where can I find": "You can find information in the respective sections.",
    "how do I": "Please specify what you need help with.",
    "how can I": "Let me know what you need help with.",
    "what is": "Please provide more context for your question.",
    "who is": "I can help with information about our services.",
    "why is": "Can you please clarify your question?",
    "when is": "Please provide more details about your query.",
    "where is": "Can you specify what you are looking for?",
    "which is": "Please provide more context for your question.",
    "how much": "Can you please specify what you are asking about?",
    "how many": "Can you please clarify what you are counting?",
    "how long": "Can you please specify what you are referring to?",

}
default_response = "Sorry, I didn’t quite get that. Could you ask differently?"

