@echo off
set ROOTDIR=C:\AgenticApps\L2C

echo Starting Data Source Simulator...
start cmd /k "cd /d %ROOTDIR% && python -m app"

echo Starting Cash Application Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.cash_application.api.service"

echo Starting Credit Management Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.credit_management.api.service"

echo Starting Dispute Resolution Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.dispute_resolution.api.service"

echo Starting LeadGeneration Service...
start cmd /k "cd /d %ROOTDIR%\BusinessServices\LeadGeneration && python run.py"

echo Starting LeadQualifiction Service...
start cmd /k "cd /d %ROOTDIR%\BusinessServices\LeadQualification && python run.py"

echo Starting Fulfillment Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.fulfillment.api.service"

echo Starting Invoicing Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.invoicing.api.service"

echo Starting Order Management Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.order_management.api.service"

echo Starting Payment Collection Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.payment_collection.api.service"

echo Starting Reporting Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.reporting.api.service"

echo Starting Analytics Service...
start cmd /k "cd /d %ROOTDIR% && python -m BusinessServices.analytics.api.service"

echo Starting API Gateway Service...
start cmd /k "cd /d %ROOTDIR%\API_Gateway && python.exe gateway.py"

echo Starting Consumer Service...
start cmd /k "cd /d %ROOTDIR% && python -m Consumer.run"

echo Starting Infrastructure Service...
start cmd /k "cd /d %ROOTDIR% && python -m Infrastructure.Auth.run"

echo All services are starting...
pause